apiVersion: skaffold/v2beta24
kind: Config
deploy:
  kustomize:
    paths:
      - ./k8s
build:
  local:
    push: false
  artifacts:
    - image: fengdu/auth
      context: ./
      jib:
        project: modules/auth
        fromImage: docker://eclipse-temurin:17
    - image: fengdu/tickets
      context: ./
      jib:
        project: modules/tickets
        fromImage: docker://eclipse-temurin:17
    - image: fengdu/frontend
      context: ./modules/frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .