secretGenerator:
- name: auth-db-secret
  literals:
  - password=123456
- name: jwt-secret
  literals:
  - jwt_secret_key=123456
resources:
  - auth-postgres-depl.yaml
  - auth-depl.yaml
  - ingress-svc.yaml