spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    driver-class-name: org.postgresql.Driver
    username: feng
    password: 1234
  liquibase:
    change-log: classpath:cloud/fengdu/ticketing/tickets/db/liquibase/changelog-master.xml
mybatis:
  config-location: classpath:cloud/fengdu/ticketing/tickets/db/mapping/mappings.xml

jwt:
  secret-key: 1234567

nats: 
  spring: 
    server: nats://localhost:4222
    connection-name: tikceting